name: Keep Alive CBRE API

on:
  schedule:
    - cron: "0,5,10,15,20,30,35,40,45,50,55 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping API
        run: |
          echo "Pinging CBRE API..."
          curl -f -L https://cbre-api.onrender.com/cbre
